import { ProjectType, ExperienceType, EducationType } from "./types";

export const projects: ProjectType[] = [
  {
    id: 1,
    title: "E-commerce Platform",
    description: "A full-featured e-commerce platform with product management, cart functionality, and payment processing.",
    image: "https://images.unsplash.com/photo-1499951360447-b19be8fe80f5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=800&q=80",
    technologies: ["React", "Node.js"],
    category: "fullstack",
    completedDate: "Mar 2023",
    codeUrl: "https://github.com",
    liveUrl: "https://example.com",
    detailsUrl: "#",
  },
  {
    id: 2,
    title: "Dashboard UI",
    description: "A responsive admin dashboard with dark mode, data visualization, and customizable widgets.",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=800&q=80",
    technologies: ["React", "Tailwind"],
    category: "frontend",
    completedDate: "Jan 2023",
    codeUrl: "https://github.com",
    liveUrl: "https://example.com",
    detailsUrl: "#",
  },
  {
    id: 3,
    title: "Fitness Tracker App",
    description: "A mobile app for tracking workouts, nutrition, and fitness goals with progress visualization.",
    image: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=800&q=80",
    technologies: ["React Native", "Firebase"],
    category: "mobile",
    completedDate: "Dec 2022",
    codeUrl: "https://github.com",
    liveUrl: "https://example.com",
    detailsUrl: "#",
  },
  {
    id: 4,
    title: "Social Media Platform",
    description: "A niche social platform with real-time messaging, user profiles, and content sharing capabilities.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=800&q=80",
    technologies: ["Next.js", "MongoDB"],
    category: "fullstack",
    completedDate: "Oct 2022",
    codeUrl: "https://github.com",
    liveUrl: "https://example.com",
    detailsUrl: "#",
  },
  {
    id: 5,
    title: "Marketing Website",
    description: "A responsive marketing website with animation effects, optimized for conversions and SEO.",
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=800&q=80",
    technologies: ["HTML/CSS", "JavaScript"],
    category: "frontend",
    completedDate: "Aug 2022",
    codeUrl: "https://github.com",
    liveUrl: "https://example.com",
    detailsUrl: "#",
  },
  {
    id: 6,
    title: "Travel Companion App",
    description: "A mobile app for travelers featuring maps, itinerary planning, and recommendations based on location.",
    image: "https://images.unsplash.com/photo-1534536281715-e28d76689b4d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=800&q=80",
    technologies: ["React Native", "APIs"],
    category: "mobile",
    completedDate: "Jun 2022",
    codeUrl: "https://github.com",
    liveUrl: "https://example.com",
    detailsUrl: "#",
  },
];

export const experiences: ExperienceType[] = [
  {
    id: 1,
    title: "Senior Frontend Developer",
    company: "TechCorp Inc.",
    description: "Led the frontend team in developing a complex SaaS platform. Implemented modern React patterns and optimized performance.",
    skills: ["React", "Redux", "TypeScript"],
    period: "2020 - Present",
  },
  {
    id: 2,
    title: "Frontend Developer",
    company: "WebSolutions Ltd.",
    description: "Developed responsive web applications and collaborated with design teams to implement pixel-perfect interfaces.",
    skills: ["JavaScript", "Vue.js", "SCSS"],
    period: "2018 - 2020",
  },
  {
    id: 3,
    title: "Junior Web Developer",
    company: "CreativeAgency",
    description: "Assisted in building client websites and internal tools. Focused on creating clean, maintainable code and enhancing user experiences.",
    skills: ["HTML/CSS", "jQuery", "WordPress"],
    period: "2016 - 2018",
  },
  {
    id: 4,
    title: "Intern",
    company: "TechStart",
    description: "Gained practical experience in web development while working on real-world projects. Learned industry best practices and teamwork.",
    skills: ["HTML/CSS", "JavaScript", "Git"],
    period: "2015 - 2016",
  },
];

export const education: EducationType = {
  degree: "B.S. Computer Science",
  school: "University of Technology",
  description: "Graduated with honors. Specialized in web technologies and software engineering.",
  period: "2011 - 2015",
};
